### ISSUE TITLE
Add git?

### ISSUE THREAD

**Issue by colindean** [kns-it/Docker-Pandoc#2]
I'm working on a build that uses `git describe` or `git log` to determine the version number of the document. `git` is not present in the container. Adding it would add about 20 MB uncompressed according to the Alpine package pages for it and its dependencies.

A workaround for now is building my own container on top but I've not yet automated detection and build-if-not-present for that, so it'd be lovely if `git` would be included in the master with one line change and a slightly larger image.

**Comment by prskr** [comment]
Right now I'm measuring the image size diff if I'd include `git` into the image.

I'd expect the build system to inject information like the commit hash as environment variables and therefore I do not really see the need to include `git` to the image :wink:

Would you mind to give me a little bit more context?

**Comment by colindean** [comment]
I've got `$(shell git log -1 --date=iso --format='%ai' | cut -c-10 )` inside a command inside of a Make task (I submitted #1 to add make, it's tiny and widely used). I _could_ move it to the global scope, passing its value into the docker command that would be in the Makefile as well:

```make
VERSION ?= $(shell git log -1 --date=iso --format='%ai' | cut -c-10 )

build-docker:
    docker run -it -v `pwd`:/home/pandoc -e VERSION="$(VERSION)" knsit/pandoc:latest make

build:
   pandoc <options> --title "Something $(VERSION)"
```

**Comment by prskr** [comment]
As Git and Make are already part of the image since a while I'm gonna close this issue :wink:
